### PR TITLE
Chat fix

### LINKED ISSUE #145: Chat is not working

### PR DESCRIPTION
**Pull request by Dletta**
Okay, took me a bit but fixed chat.

I had to change the emitter for Internal and Ext Messages, used metaData.send( to send it across and metaDatareceived to get it back.
For mobile I added a button at the bottom and hooked it up to the same event.

@jacovinus I had to add padding to chatmessages div, otherwise it cut off messages!

Currently you can still send html, which is how we can paste links when we want to send them across, ;). So it's a feature.

Closes #145 .

### CODE REVIEW

**Comment by Dletta** [comment]
Also fixed issue #119 just now

File: src/assets/js/modal.js [hunk 1]
```diff
@@ -129,7 +129,9 @@ export default class Modal {
                 sessionStorage.setItem('username', yourName);
                 //create room link
                 let roomgen = lib.roomgen(roomName,med.h.generateRandomString())
-                let roomLink = lib.roomLink(location.origin,roomgen) 
+                // save room name in sessionStorage
```
Comment (QVDev) [inline src/assets/js/modal.js:132]: Saving it to the session is one way to solve it. But I thought when people logout using the red button, it should maybe just go to the room url again this way we wont loose the room or is this assumption incorrect?

File: src/assets/js/sfu/room.js [hunk 2]
```diff
@@ -19,6 +19,7 @@ export default class Room extends EventEmitter {
             var SFU_URL = "wss://" + window.location.hostname + ":2345";
             console.log("Joining Local SFU", SFU_URL);
             const wsTransport = new WebSocket(`${SFU_URL}/?roomId=${room}&peerId=${peerId}`, "protoo");
+            if(!wsTransport.onopen){throw 'local connection not working'};
```
Comment (QVDev) [inline src/assets/js/sfu/room.js:22]: It should throw, and come in the failback situation of weird this did not happen with you

File: src/index.html [hunk 3]
```diff
@@ -27,8 +27,8 @@
   <script src="/assets/js/soundmeter.js" type="text/javascript"></script>
   <script type="module" src="/assets/js/emitter.js"></script>
   <script type="module" src="/assets/js/main.js"></script>
-  <script type="module" src="/assets/js/events.js"></script>
-  <!--<script type="module" src="/assets/js/rtc.js"></script> -->
+  <!-- <script type="module" src="/assets/js/events.js"></script> -->
```
Comment (QVDev) [inline src/index.html:30]: Can be removed is commented out and dead code, git has a history in case we wanna get it back later on

File: src/index.html [hunk 4]
```diff
@@ -109,8 +109,11 @@
         <div id="chat-messages"></div>
 
         <div class="row">
-          <textarea id="chat-input" class="form-control rounded-0 chat-box border-info" rows="3"
-            placeholder="Type here..."></textarea>
+          <textarea id="chat-input" class="form-control rounded-0 chat-box border-info" rows="1"
+            placeholder="Type here..."></textarea><br>
+          <button id="chat-send" class="form-control btn btn-primary rounded-0 chat-button">
+            <i class="fas fa-paper-plane"></i>
```
Comment (QVDev) [inline src/index.html:115]: M.I.A. Paper planes https://www.youtube.com/watch?v=ewRjZoRtu0Y

File: src/assets/js/chat.js [hunk 5]
```diff
@@ -1,5 +1,125 @@
...
+        return false;
+    }
+  }
+
+  showInChat (data, senderType) {
+    if (data == self.cache) {
+      self.cache = null;
+      return;
+    }
+    let chatMsgDiv = document.querySelector("#chat-messages");
```
Comment (QVDev) [inline src/assets/js/chat.js:79]: Do we still nee document and UEX stuff in here?

File: src/assets/js/chat.js [hunk 6]
```diff
@@ -1,5 +1,125 @@
...
+  async showTime(timezone, data) {
+      let response = await fetch("https://worldtimeapi.org/api/timezone/" + timezone);
+      if (response.ok) {
+          let json = await response.json();
+          data.msg = json.datetime;
+          this.showInChat(data);
+      }
+  }
+
+//////
```
Comment (QVDev) [inline src/assets/js/chat.js:124]: These ///// can be removed

File: src/index.html (hunk 3 above)
Comment (QVDev) [reply src/index.html:30]: - [x] patch myself

File: src/assets/js/chat.js (hunk 5 above)
Comment (QVDev) [reply src/assets/js/chat.js:79]: - [x] @Dletta or @jacovinus will pick this up later not critical

File: src/assets/js/chat.js (hunk 6 above)
Comment (QVDev) [reply src/assets/js/chat.js:124]: - [x] patch myseld
